name: CI

on:
  release:
    types:
      - released
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get current time
        uses: 1466587594/get-current-time@v2
        id: current-time
        with:
          format: YYYYMMDDTHHmmss
          utcOffset: "+08:00"

      - uses: actions/checkout@v3
        with:
          lfs: true

      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - uses: gradle/gradle-build-action@v2
        with:
          arguments: assembleRelease bundlePlayRelease
        env:
          PASSWORD: "${{ secrets.PASSWORD }}"

      - name: PreRelease Package
        uses: marvinpinto/action-automatic-releases@latest
        if: github.event_name == 'workflow_dispatch' || github.event_name == 'push'
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "${{ steps.current-time.outputs.formattedTime }}"
          prerelease: true
          files: |
            app/build/outputs/apk/github/release/*
            app/build/outputs/apk/free/release/app-free-release.apk

      - name: Release Package
        uses: marvinpinto/action-automatic-releases@latest
        if: github.event_name == 'release'
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "${{ github.event.release.tag_name }}"
          prerelease: false
          files: |
            app/build/outputs/apk/github/release/*
            app/build/outputs/apk/free/release/app-free-release.apk

      - name: Get apk info
        id: apk-info
        uses: hkusu/apk-info-action@v1
        with:
          apk-path: app/build/outputs/apk/appcenter/release/app-appcenter-release.apk

      - name: Setup AppCenter CLI
        run: |
          npm install -g appcenter-cli

      - name: Upload artifact to App Center
        run: |
          bash ./scripts/appcenter.sh
        env:
          VERSION_CODE: ${{ steps.apk-info.outputs.version-code }}
          VERSION_NAME: ${{ steps.apk-info.outputs.version-name }}
          APPCENTER_TOKEN: ${{ secrets.APPCENTER_TOKEN }}